services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pg-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d ${DB_NAME} -U ${DB_USER}
      interval: 15s
      timeout: 20s
      retries: 10
    ports:
      - 5432:5432
  objects:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      # - MINIO_DOMAIN=127.0.0.1
      - MINIO_ACCESS_KEY=${MINIO_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET}
      - 9001:9001
    volumes:
      - minio-data:/data
  server:
    build:
      context: ./Server
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=8080
      - MINIO_HOST=objects
      - MINIO_PORT=9000
      - MINIO_KEY=${MINIO_KEY}
      - MINIO_SECRET=${MINIO_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - IMAGE_URL_PREFIX=http://localhost/assets/
  nginx:
    image: nginx:alpine
    restart: always
    environment:
      - SERVER=server:8080
      - OBJECTS=objects:9000
      - SERVER_NAME=localhost
    volumes:
      - ./net/nginx.conf:/etc/nginx/templates/default.conf.template:ro
    ports:
      - 80:80
    depends_on:
      - server
      - objects
volumes:
  pg-db:
  minio-data: