CREATE TYPE "ROLE_ENUM" AS ENUM ('OWNER', 'ADMIN', 'USER');
CREATE CAST (varchar AS "ROLE_ENUM") WITH INOUT AS IMPLICIT;

CREATE TABLE "User" (
    userId UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role "ROLE_ENUM" NOT NULL
);